---
# groups of groups and/or users
# metafilter by scientific discipline or location
metagroups:
  chimie_ENS:
    chimie
    lch
    rmn
    rcaracas
  chimie_UdL:
    ilm
    crmn
    dpm
    icbms
    isa
    lasim
    lmi
  bio_ENS:
    bio
    cbvi
    ciri
    igfl
    lbmc
    rdp
  physique_ENS:
    cbp
    cecam
    ixxi
    lph
    phys
  autres_ENS:
    # catchall
    citi
    gate
    ihrim
    umpa
    psmn
    maply
  cral_ENS:
    cral
  partenaires_ENS:
    cssi
    prolb
  geol_ENS:
    geol
    lgl
    ipag
  lmfa_ECL:
    insa
    lmfa
  lip_ENS:
    lip
